jeanphilippe_blog:
    resource: "@JeanphilippeBlogBundle/Resources/config/routing.yml"
    prefix:   /Blog

app:
    resource: "@AppBundle/Controller/"
    type:     annotation

blog:
    resource: "@JeanphilippeBlogBundle/Controller/"
    type:     annotation
