services:
    jeanphilippe_blog.slugger:
        class: Jeanphilippe\BlogBundle\Service\Slugger
#        arguments: [@service_id, "plain_value", %parameter%]
    jeanphilippe_blog.article_listener:
        class: Jeanphilippe\BlogBundle\Service\SlugListener
        calls:
            - [setSlugger, ["@jeanphilippe_blog.slugger"]]
        tags:
            - { name: doctrine.event_listener, event: preUpdate }
            - { name: doctrine.event_listener, event: prePersist }
